
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class I2 : Luban.BeanBase
    {
        public I2(ByteBuf _buf) 
        {
            Key = _buf.ReadString();
            Key_Ref = null;

            EndInit();
        }

        public static I2 DeserializeI2(ByteBuf _buf)
        {
            return new I2(_buf);
        }

        public readonly string Key;
        public LocalizationCheckConfig Key_Ref;
    
        public const int __ID__ = 2313;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            Key_Ref = LocalizationCheckConfigCategory.Instance.GetOrDefault(Key);
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "key:" + Key + ","
            + "}";
        }

        partial void EndRef();
    }

}

