
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class LocalizationCheckConfig : Luban.BeanBase
    {
        public LocalizationCheckConfig(ByteBuf _buf) 
        {
            Key = _buf.ReadString();

            EndInit();
        }

        public static LocalizationCheckConfig DeserializeLocalizationCheckConfig(ByteBuf _buf)
        {
            return new LocalizationCheckConfig(_buf);
        }

        public readonly string Key;
    
        public const int __ID__ = -716489231;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "key:" + Key + ","
            + "}";
        }

        partial void EndRef();
    }

}

