
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class GameObjectPoolSettingsConfig : Luban.BeanBase
    {
        public GameObjectPoolSettingsConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadString();
            Timeout = _buf.ReadFloat();
            MaxCacheCount = _buf.ReadInt();
            CacheTime = _buf.ReadFloat();
            MinCacheCount = _buf.ReadInt();
            MaxCacheCountNewResName = _buf.ReadString();

            EndInit();
        }

        public static GameObjectPoolSettingsConfig DeserializeGameObjectPoolSettingsConfig(ByteBuf _buf)
        {
            return new GameObjectPoolSettingsConfig(_buf);
        }

        /// <summary>
        /// 资源名称
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// 最大显示时间 &lt;=0 表示永不过期
        /// </summary>
        public readonly float Timeout;
        /// <summary>
        /// 同时显示的最大数量 &lt;=0 表示不限制
        /// </summary>
        public readonly int MaxCacheCount;
        /// <summary>
        /// 缓存池中保留的时间 &lt;=0 表示永久保留
        /// </summary>
        public readonly float CacheTime;
        /// <summary>
        /// 缓存池中的最大数量 &lt;0 表示不限制 默认 -1
        /// </summary>
        public readonly int MinCacheCount;
        /// <summary>
        /// 超过最大显示时 返回一个新的资源
        /// </summary>
        public readonly string MaxCacheCountNewResName;
    
        public const int __ID__ = 1681540178;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "timeout:" + Timeout + ","
            + "MaxCacheCount:" + MaxCacheCount + ","
            + "CacheTime:" + CacheTime + ","
            + "MinCacheCount:" + MinCacheCount + ","
            + "MaxCacheCountNewResName:" + MaxCacheCountNewResName + ","
            + "}";
        }

        partial void EndRef();
    }

}

