
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class GameObjectPoolSettingsConfigCategory : Singleton<GameObjectPoolSettingsConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<string, GameObjectPoolSettingsConfig> _dataMap;
        private readonly List<GameObjectPoolSettingsConfig> _dataList;
        
        public GameObjectPoolSettingsConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<string, GameObjectPoolSettingsConfig>();
            _dataList = new List<GameObjectPoolSettingsConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                GameObjectPoolSettingsConfig _v;
                _v = global::ET.GameObjectPoolSettingsConfig.DeserializeGameObjectPoolSettingsConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<string, GameObjectPoolSettingsConfig> GetAll() => _dataMap;
        public Dictionary<string, GameObjectPoolSettingsConfig> DataMap => _dataMap;
        public List<GameObjectPoolSettingsConfig> DataList => _dataList;

        public GameObjectPoolSettingsConfig GetOrDefault(string key) => _dataMap.GetValueOrDefault(key);

        public GameObjectPoolSettingsConfig Get(string key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

